### ISSUE TITLE
Problems preventing “outsiders” from building

### ISSUE THREAD

**Issue by a4lg** [dthaler/OTrP#3]
I spent days on your Visual Studio solution and I'm still struggling with it. It seems this solution has something we (outside of Microsoft) don't have access to.

# Issues

## 1. Package dependency is wrong

As you correctly added on commit 0ae80d4c0d10ba343bf0fe5df0655300bdcb3ec3, all projects require `open-enclave-cross` package. But most of the project files are not updated and depends on `open-enclave` (which doen't have correct `.targets` file).

I used following shell script to update all dependencies:

```sh
find -type f -name '*.vcxproj' -print0 | xargs -r -0 sed -i 's/open-enclave\.0\.8\.0-rc1/open-enclave-cross.0.8.1-c3b6262c-2/g'
find -type f -name '*.vcxproj' -print0 | xargs -r -0 sed -i 's/\\open-enclave\.targets/\\open-enclave-cross\.targets/g'
find -type f -name packages.config -print0 | xargs -r -0 sed -i 's/id="open-enclave" version="0.8.0-rc1"/id="open-enclave-cross" version="0.8.1-c3b6262c-2"/'
```

## 2. `jansson.h` cannot be included

While there is `jansson.h` in `external/jansson/src`, it seems some project files assume that `jansson.h` is located at `external/jansson/include` or something.  It looks we need to update `AdditionalIncludeDirectories` correctly.

I changed the source code to make `TeepAgentBrokerLib` work but it seems following three project require same kind of thanges (but we cannot test because of (4)):

* `TeepAgentTA`
* `TeepTamTA`
* `TeepCommonTALib`

## 3. What is `MyEnclave2`?

`DeviceHost` project has unknown dependency to an enclave named `MyEnclave2`. I think this is the test code and should be removed from the project.

## 4. Missing platform toolset `Open Enclave (v142)`

I think this is a part of Open Enclave Visual Studio extension or something (which haven't released yet).

# Possible Cause?

I can only imagine but there is possible cause of (2) and (3): source code in the work tree but not managed by git.

# Fix

For complete fix, it needs your work. For issues (1) through (3) (only applies on untrusted part of the solution), I have partial fix and will pull-request later.

**Comment by dthaler** [comment]
The extension is temporarily available at https://1drv.ms/u/s!Aqj-Bj9PNivcnvAKGa6fr8AlGk_a0g?e=am23nd until it appears in the VS marketplace.   Please test using that one and let me know whether you still have issues.

Thanks for the other fixes!

**Comment by dthaler** [comment]
@a4lg let me know if the above info unblocks you.

**Comment by a4lg** [comment]
It _mostly_ worked (except three issues):

## 1. Additional `jansson.h` path issues [Fixed in upcoming PR]

Commit e305f8e89fde049eba092ddc1eb205c6f361ae66 fixes proper include path to `jansson.h` _only for projects I could test_. I checked again and following projects need to be updated.

* TeepAgentTA
* TeepCommonTALib
* TeepTamTA
* UntrustedTimeLib (host)
* jansson (also source file location)
* LibEay32

I also made tentative change to LibEay32 (make `Release|x64` include directories same as `Debug|x64`).


## 2. `libeay32/sgx/rand_winsgx.c` [Fixed in upcoming PR]

It uses `oe_random` function but doesn't include `<openenclave/enclave.h>`.


## 3. OpenSSL

Before your awesome comment, I tried porting this solution to CMake and once stuck at OpenSSL.  It seems `opensslconf.h` is required and all public OpenSSL header files must be placed under `openssl` directory.

I made a workaround of this issue as follows:

1. [WSL] Run `./Configure linux-x86_64` on `external/openssl`
2. [WSL] It makes `external/openssl/include/openssl` directory but this is useless alone because of symbolic links (junctions in Windows). I ran following shell script on `external/openssl/include` to convert symbolic links to regular files: `find -type l | while read LINKFROM; do LINKTO=$(readlink $LINKFROM); rm $LINKFROM; cp $LINKTO $LINKFROM; done`
3. Add `$(SolutionDir)external/openssl/include` to relevant projects' include path.
4. Compiling solution caused link errors because of `#define OPENSSL_CPUID_OBJ` line in `external/openssl/include/openssl/opensslconf.h` so I commented that out.

After this workaround... it builds (from scratch)!

... yet I have to admit that this is not clean so this workaround is NOT included in upcoming pull-request. I think we need instructions for building OpenSSL for enclaves and add proper include path.

To do step 3 in this solution, following projects need to be updated:

* LibEay32
* jose_openssl
* TeepAgentTA
* TeepCommonTALib
* TeepTamTA

And note that, if full path to the solution is too long (not too long in general sense), it fails to run the linker.

**Comment by dthaler** [comment]
I've updated the VSIX to no longer depend on EnclaveCommonAPI and merged PR #5.  There is still an issue remaining due to converting from the Win32 platform (which worked with the old OE SDK release) to the x64 platform (since Win32 is no longer supported by the current OE SDK release).  Working on that now.

**Comment by dthaler** [comment]
FYI, when Win32 was used the solution built by running the openssl do_ms.bat script but since we now use x64 we have to update the instructions.

**Comment by dthaler** [comment]
@a4lg I believe this issue is now all resolved, assuming you have the latest VSIX installed (see link in prerequisites section in the [README](https://github.com/dthaler/OTrP)).  Please test and reopen this issue if it is not working for you.
